name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: 
  contents: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.14'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: |
        cd .github/ActionTesting
        go build --tags=actiontesting -o=../../ActionTesting
        cd ../..
        ./ActionTesting
